#!/bin/bash
#ver. 3
##this script will check mysql and apache
##if that service is not running
##it will start the service and send 
##an email to you

##set the path ##this works for Ubuntu 14.04 and 16.04
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

##set your email address 
EMAIL="youremail@domain.com"

##list your services you want to check
SERVICES=(  'mysql' 'apache2'  )

#### OK. STOP EDITING ####




 for i in "${SERVICES[@]}"
  do
###CHECK SERVICE####
`pgrep $i >/dev/null 2>&1`
STATS=$(echo $?)

###IF SERVICE IS NOT RUNNING####
if [[  $STATS == 1  ]]

then

##TRY TO RESTART THAT SERVICE###
service $i start

##CHECK IF RESTART WORKED###
`pgrep $i >/dev/null 2>&1`
RESTART=$(echo $?)

if [[  $RESTART == 0  ]]
##IF SERVICE HAS BEEN RESTARTED###
then
##SEND AN EMAIL###
MESSAGE="$i   is down, but looks like I was able to restart it on   on $(hostname) $(date)  "
SUBJECT="$i  down -but restarted-  on $(hostname) $(date) "
echo   $MESSAGE | mail -s "$SUBJECT" "$EMAIL"

else
##IF RESTART DID NOT WORK SEND A DIFFERENT EMAIL###
MESSAGE="$i is down   on $(hostname)  at $(date)  "
SUBJECT=" $i  down on $(hostname) $(date) "
echo $MESSAGE  " I tried to restart it, but it did not work"  | mail -s "$SUBJECT" "$EMAIL"

fi
fi

  done
